#!/usr/bin/env sh

# the get_tasks function reads a file, then prints the current time, as well as time the task will be completed
# how do you change this to output the remaining time to finish the task
get_tasks() {
  tasks=$(cat /tmp/tasks)
  if [[ -z $tasks ]]; then
    tasks="not set"  
  else
    completed_time=$((10#$(echo $tasks | awk '{print $3}')))
    if [[ completed_time -gt 2359 ]]; then
      completed_time=$((10#$completed_time-2400))
      tasks="$(echo $tasks | awk '{print $1,$2}' ) $(printf "%04d" $completed_time)"
    fi
  fi
  if [[ $tasks == "not set" ]]; then
    echo "{\"name\": \"tasks\", \"full_text\": \"\" }"
    return
  fi
  echo "{\"name\": \"tasks\", \"full_text\": \"CUR: $tasks\" }"
  return
}

get_countdown() {
  timer_start=$(cat /tmp/timer_start) 
  if [[ -z $timer_start ]]; then
    echo "{\"name\": \"tasks\", \"full_text\": \"\" }" 
  else
    current_time=$(date +'%s')
    countdown=$((10#$current_time - 10#$timer_start ))
    # format countdown to hhmmss
    countdown=$(date -u -d @${countdown} +'%H:%M:%S')
    echo "{\"name\": \"tasks\", \"full_text\": \"$countdown\" }"
  fi
}

get_cryp() {
  pc=$(curl -s https://api.coindesk.com/v1/bpi/currentprice/BTC.json | jq -r '.bpi.USD.rate' | sed "s/,//g" | sed "s/\.//g")
  echo "{\"name\": \"btc\", \"full_text\": \"$pc\" }"
}

get_bat() {
  bat=$(cat /sys/class/power_supply/BAT0/capacity)
  if [[ bat -le 20  ]]; then
    color="#cc241d"
  else
    color="#d79921"
  fi
  echo "{\"name\": \"battery\", \"full_text\": \"$bat\", \"color\": \"$color\" }"
}

get_charging() {
  charging=$(cat /sys/class/power_supply/AC/online)
  if [[ charging -eq 1 ]]; then
    color="#d79921"
  else
    color="#282828"
  fi
  echo "{\"name\": \"charging\", \"full_text\": \"$charging\", \"color\": \"$color\" }" 
}

get_mem() {
  mem=$(free -h | grep Mem | awk '{print $3}' | sed "s/[a-Z]//g")
  echo "{\"name\": \"mem\", \"full_text\": \"$mem\" }"
}

get_date() {
  date=$(date +'%H%M')
  echo "{\"name\": \"date\", \"full_text\": \"$date\" }"
}

get_day() {
  day=$(date +'%A')
  echo "{\"name\": \"day\", \"full_text\": \"$day\" }"
}
 
#282828
#cc241d
#98971a
#d79921
#458588
#b16286
#689d6a
#a89984

get_status() {
  echo -n "["
  get_countdown
  echo ","
  get_mem 
  echo ","
  get_date 
  echo ","
  get_bat
  echo ","
  get_charging 
  # get_day
  # echo ","
  # get_cryp
  # echo ","
  echo "]"
} 

echo "{ \"version\": 1 }"
echo "["
get_status
echo ","
sleep 1

while true; do 
  get_status
  echo ","
  sleep 1 
done 
