 icons_format = "{icon}"

[theme]
theme = "slick"

[icons]
icons = "awesome5"
[icons.overrides]
bat = " | | "
bat_full = " |X| "
bat_charging = " |^| "
bat_discharging = " |v| "


[[block]]
block = "memory"
format = "  $mem_used_percents.eng(w:1) "
format_alt = " $icon_swap $swap_free.eng(w:3,u:B,p:M)/$swap_total.eng(w:3,u:B,p:M)($swap_used_percents.eng(w:2)) "
interval = 30
warning_mem = 70
critical_mem = 90
[block.theme_overrides]
idle_bg = "#45475a"
idle_fg = "#74c7ec"

[[block]]
block = "cpu"
interval = 1
format_alt = " $icon $frequency{ $boost|} "
[block.theme_overrides]
idle_bg = "#313244"
idle_fg = "#f9e2af"

[[block]]
block = "net"
device = "eno1"
[block.theme_overrides]
idle_bg = "#1e1e2e"
idle_fg = "#89b4fa"

[[block]]
block = "sound"
[block.theme_overrides]
idle_bg = "#181825"
idle_fg = "#fab387"

[[block]]
block = "time"
interval = 60
format = " $icon $timestamp.datetime(f:'%m/%d %I:%M %p') "
[block.theme_overrides]
idle_bg = "#11111b"
idle_fg = "#a6e3a1"     
