local key = require("keymap.key")
local nmap = key.nmap

nmap("<leader>li", ":LspInfo<CR>", "lsp: info")
nmap("<leader>lr", ":LspRestart<CR>", "lsp: restart")
nmap("go", ":Lspsaga outline<CR>", "lsp: restart")
nmap("g[", ":Lspsaga diagnostic_jump_prev<CR>", "lsp: Prev diagnostic")
nmap("g]", ":Lspsaga diagnostic_jump_next<CR>", "lsp: Next diagnostic")
nmap("<leader>ld", ":Lspsaga show_line_diagnostics<CR>", "lsp: show line diagnostics")
nmap("gr", ":Lspsaga rename<CR>", "lsp: rename")
nmap("gR", ":Lspsaga rename ++project<CR>", "lsp: rename in project")
nmap("ga", ":Lspsaga code_action<CR>", "lsp: code action")
nmap("gd", ":Lspsaga peek_definition<CR>", "lsp: peek definition")
nmap("gD", ":Lspsaga goto_definition<CR>", "lsp: goto definition")
nmap("K", ":Lspsaga hover_doc<CR>", "lsp: show doc")
