local key = require("keymap.key")
local nmap = key.nmap

nmap("<leader>D", "<Cmd>DiffviewOpen<CR>", "git: show diff")
nmap("<leader>C", "<Cmd>DiffviewClose<CR>", "git: show diff")


nmap("<leader>li", ":LspInfo<CR>", "lsp: info")
nmap("<leader>lr", ":LspRestart<CR>", "lsp: restart")
nmap("g[", function ()
  vim.diagnostic.jump({count = -1})
	vim.diagnostic.open_float()
end, "lsp: Prev diagnostic")
nmap("g]", function()
	vim.diagnostic.jump({ count = 1 })
	vim.diagnostic.open_float()
end, "lsp: Next diagnostic")
nmap("gl", function()
	vim.diagnostic.open_float()
end, "lsp: show line diagnostics")
nmap("gr", function()
	vim.lsp.buf.rename()
end, "lsp: rename")
nmap("ga", function()
	vim.lsp.buf.code_action()
end, "lsp: code action")
nmap("gd", function()
	vim.lsp.buf.definition()
end, "lsp: goto definition")
nmap("K", function()
	vim.lsp.buf.hover()
end, "lsp: show doc")
