#!/usr/bin/env bash

bak=$IFS
IFS=$' '
while true
do
 tasks=$(cat /tmp/tasks)
 [[ -z $tasks ]]  && notify-send -t 2000 --urgency=CRITICAL   "Tasks:" "No task created" && sleep 20 && continue  
 read -ra arr <<< $(cat /tmp/tasks)
 d=$(date +'%H%M')
 task_time="${arr[-1]}"
 d=$((10#$d))
 task_time=$((10#$task_time))
if [[ $task_time -gt 2359 ]]; then
    $task_time=$(($task_time - 2400))
fi
if [[ task_time -le $d ]]; then
  notify-send "Task" "Completed" 
  echo "" > /tmp/tasks
 fi
 sleep 60
done
exit
IFS=$bak
