#!/bin/bash

show_remider() {
	CONTINUE=$(
		zenity --question --text="Did you check daily tasks?" --ok-label="Yes" --cancel-label="No" --display=:0.0
		echo $?
	)
  echo $CONTINUE
}
 
if which emacs &>/dev/null; then 
  is_installed=1
else
  is_installed=0
fi

response=$(show_remider)
echo "$response"

if [[ $response == "1" ]]; then
  if [[ is_installed -eq 1 ]]; then 
    echo "opening emacs"
    emacs ~/projects/notes/daily/daily.org
  fi 
fi
