#!/usr/bin/env bash

source ~/.config/scripts/configvars.sh

task=$(echo "" | $dmenu_prompt "Task: ")
[[ -z $task ]] && notify-send "Task aborted" && exit 
time=$(echo "" | $dmenu_prompt "Time: ")
[[ -z $time ]] && notify-send "Task aborted" && exit 
notify-send "Task" "$task in $time"
d=$(date +'%H%M')
new_time=$((10#$d + 10#$time))
 echo "$task $(date +'%H%M') $new_time" > /tmp/tasks
