#!/usr/bin/env bash

source ~/.config/scripts/configvars.sh

task=$(echo "" | $dmenu_prompt "Task: ")
[[ -z $task ]] && notify-send "Task aborted" && exit 
time=$(echo "" | $dmenu_prompt "Time: ")
[[ -z $time ]] && notify-send "Task aborted" && exit 
d=$(date +'%H%M')
time=$(( 10#$time ))
min=$(( $time % 100 )) 
hr=$(( $time / 100 )) 
notify-send "Task" "$task for $hr hr $min min"
new_time=$(date -d "+$hr hour +$min min" +"%H%M")
 echo "$task $(date +'%H%M') $new_time" > /tmp/tasks
