#!/bin/bash


function notify_vol
{
  status=$(awk -F"[][]" '/Left:/ {print $4}' <(amixer sget Master))
  # volume=$(awk -F"[][]" '/Left:/ { print $2 }' <(amixer sget Master) | sed 's/%//g' )
  volume=$(pamixer --get-volume)

  if  [[ $volume -eq 1 ]]; then
    dunstify "0"   -t 800 -r 91190 -i ~/.config/scripts/images/unmuted.svg
    return
  fi
  bar=$(seq -s "󰝤" $(($volume / 5)) | sed 's/[0-9]//g' )
  bar+=$(seq -s " " $(($volume / 5)) | sed 's/[0-9]//')
  dunstify "$volume" $bar -a "Volume: " -t 800 -r 91190 -i ~/.config/scripts/images/unmuted.svg
}

function notify_mute
{
    mute=`pamixer $srce --get-mute | cat`
    if [ "$mute" == "true" ] ; then
        dunstify "t2" -a "muted" "$nsink" -i ${icodir}/muted-${dvce}.svg -r 91190 -t 800
    else
        dunstify "t2" -a "unmuted" "$nsink" -i ${icodir}/unmuted-${dvce}.svg -r 91190 -t 800
    fi
}

case "$1" in
  volume|vol) 
  status=$(awk -F"[][]" '/Left:/ {print $4}' <(amixer sget Master))
  volume=$(awk -F"[][]" '/Left:/ { print $2 }' <(amixer sget Master))
  if [[ $status == "on" ]]; then
    if [[ -e ~/.config/scripts/images/unmuted.svg ]]; then
      notify_vol
    else
      notify-send -t 500 "muted $volume"
      exit 0
    fi
  else
    if [[ -e ~/.config/scripts/images/muted.svg ]]; then
      notify-send -t 500 -i ~/.config/scripts/images/muted.svg " $volume"
    else
      notify-send -t 500 " $volume"
    fi
  fi
  ;;
  bat|battery) 
    battery="$(cat /sys/class/power_supply/BAT0/capacity)"
    charging="$(cat /sys/class/power_supply/AC/online)"
    if [[ "$charging" == 1 ]]; then
      notify-send -t 2000 -i ~/.config/scripts/images/battery-bolt-alt-svgrepo-com.svg  "Level: $battery%"
    else
      if [[ "$battery" -gt 90 ]]; then 
        notify-send -t 2000 -i ~/.config/scripts/images/battery-full.svg "Level: $battery%"
      elif [[ "$battery" -gt 60 ]]; then
        notify-send -t 2000 -a ""  -i ~/.config/scripts/imagees/battery-mid.svg  "Level: $battery%"
      elif [[ "$battery" -gt 30 ]]; then 
        notify-send -t 2000 -a "" -i ~/.config/scripts/images/battery-low.svg "Level: $battery%"
      else 
        notify-send -t 2000 -a "" -i ~/.config/scripts/images/battery-slash-svgrepo-com.svg "Level: $battery%"
      fi

    fi
  ;;
  time)
    time="$(date '+%H:%M:%S')"
    notify-send -t 2000 -a "" -i ~/.config/scripts/images/clock.svg "$time"
  ;;
  *) echo default
  ;;
esac
