#!/bin/bash


function notify_vol
{
  # status=$(awk -F"[][]" '/Left:/ {print $4}' <(amixer sget Master))
  # volume=$(awk -F"[][]" '/Left:/ { print $2 }' <(amixer sget Master) | sed 's/%//g' )
  volume=$(pamixer --get-volume)

  if  [[ $volume -eq 1 ]]; then
    dunstify "0"   -t 800 -r 91190 
    return
  fi
  notify-send "$volume" "Volume: " -h int:value:$volume -t 800 -r 91190 
  echo "$volume"
}

function notify_mute
{
    volume=$(pamixer --get-volume)
    notify-send "Muted" "$volume" -a "Muted " -h int:value:$volume -t 800 -r 91190 
}

function notify_brightness 
{
  brightness=$(light)
  notify-send "$(light)" -a "Brightness: " -h int:value:$brightness -t 800 -r 91190 
}

case "$1" in
  volume|vol) 
    case "$2" in 
      pamixer)
      if [[ $status == "false" ]]; then
          notify_vol
      else
          notify_mute
      fi
      ;;
      amixer|alsa)
      volume=$(awk -F"[][]" '/Left:/ { print $2 }' <(amixer sget Master))
      mute=`amixer get Master | grep -o "\[off\]" | head -1 `
      if [ -n "$mute"  ] ; then
        notify-send "$volume"  "Muted " -h int:value:$volume -t 800 -r 91190 
      else 
        notify-send "$volume" -h int:value:$volume -t 800 -r 91190 
      fi
    ;;
  esac
  ;;
  bright|brightness)
    notify_brightness
  ;;
  bat|battery) 
    battery="$(cat /sys/class/power_supply/BAT0/capacity)"
    charging="$(cat /sys/class/power_supply/AC/online)"
    if [[ "$charging" == 1 ]]; then
      notify-send -t 2000 -i ~/.config/scripts/images/battery-bolt-alt-svgrepo-com.svg  "Level: $battery%"
    else
      if [[ "$battery" -gt 90 ]]; then 
        notify-send -t 2000 -i ~/.config/scripts/images/battery-full.svg "Level: $battery%"
      elif [[ "$battery" -gt 60 ]]; then
        notify-send -t 2000 -a ""  -i ~/.config/scripts/imagees/battery-mid.svg  "Level: $battery%"
      elif [[ "$battery" -gt 30 ]]; then 
        notify-send -t 2000 -a "" -i ~/.config/scripts/images/battery-low.svg "Level: $battery%"
      else 
        notify-send -t 2000 -a "" -i ~/.config/scripts/images/battery-slash-svgrepo-com.svg "Level: $battery%"
      fi

    fi
  ;;
  time)
    time="$(date '+%H:%M:%S')"
    notify-send -t 2000 -a "" -i ~/.config/scripts/images/clock.svg "$time"
  ;;
  *) echo default
  ;;
esac
