#!/bin/sh

source ~/.config/scripts/configvars.sh

file="$HOME/.todo"
touch "$file"
height=$(wc -l "$file" | awk '{print $1}' )

cmd=$($rofi  <"$file")
while [ -n "$cmd" ]; do
	if grep -q "^$cmd\$" "$file"; then
		grep -v "^$cmd\$" "$file" >"$file.$$"
		mv "$file.$$" "$file"
		height=$((height - 1))
	else
		echo "$cmd" >>"$file"
		height=$((height + 1))
	fi

	cmd=$($rofi <"$file")
done

exit 0
