#!/bin/sh

dmenu="bemenu -c -i --bdr #bd93f9 -b -B 1 --tb #24283b --nb #24283b --nf #fff --hf #bd93f9 --hb #24283b --tf #bd93f9 --fb #24283b --ab #24283b"

file="$HOME/.todo"
touch "$file"
height=$(wc -l "$file" | awk '{print $1}')
prompt="Add/delete a task: "

cmd=$($dmenu -l "$height" -p "$prompt" "$@" --fn 'TerminessTTF Nerd Font 13' < "$file")
while [ -n "$cmd" ]; do
 	if grep -q "^$cmd\$" "$file"; then
		grep -v "^$cmd\$" "$file" > "$file.$$"
		mv "$file.$$" "$file"
        height=$(( height - 1 ))
 	else
		echo "$cmd" >> "$file"
		height=$(( height + 1 ))
 	fi

	cmd=$($dmenu -l "$height" -p "$prompt" "$@" < "$file")
done

exit 0
