#!/bin/bash

source ~/.config/scripts/configvars.sh

current_workspace=$(swaymsg -t get_workspaces | jq -r '.[] | select(.focused==true) | .name')
current_output=$(swaymsg -t get_outputs | jq -r '.[] | select(.focused==true) | .name')

refile_with_workspace=$(echo "" | $rofi_prompt "Swap with workspace:")

[[ -z $refile_with_workspace ]] && notify-send "Workspace Swap" "Swap aborted" && exit 0

workspace_exists=$(swaymsg -t get_workspaces | jq -r '.[] | .name' | grep -q "^$refile_with_workspace$")
if [[ $refile_with_workspace == $current_workspace ]]; then
    notify-send "Workspace Swap" "Cannot swap a workspace with itself."
    exit 1
elif ! $workspace_exists; then
    notify-send "Workspace Swap" "Workspace '$refile_with_workspace' does not exist."
    exit 1
fi

notify-send "Workspace Swap" "Swapping contents of '$current_workspace' and '$refile_with_workspace'..."

swaymsg "workspace tmp_swap_workspace"

swaymsg "[workspace=\"$current_workspace\"] move container to workspace tmp_swap_workspace"

swaymsg "workspace $refile_with_workspace"

swaymsg "[workspace=\"$refile_with_workspace\"] move container to workspace $current_workspace"

swaymsg "workspace tmp_swap_workspace"

swaymsg "[workspace=\"tmp_swap_workspace\"] move container to workspace $refile_with_workspace"

swaymsg "workspace $current_workspace"

swaymsg "workspace $refile_output"
swaymsg "workspace $current_workspace"

notify-send "Workspace Swap" "Contents of '$current_workspace' and '$refile_with_workspace' have been swapped."
