#!/usr/bin/env sh

usage=$(cat << EOF 
Usage: sway-goto-if-not-start [WORKSPACE] [NAME] [COMMAND]
Description:
Goto workspace if the applcation is already running in that workspace, otherwise launch the applcation
Arguments:
WORKSPACE             The name of the workspace to goto 
NAME            The program to check for 
COMMAD            The commmand to run to launch the program
EOF
)

if [[ -z $3 ]]; then
   echo "$usage"  
   exit
fi

is_emacs_running=$(swaymsg -t get_tree | jq --arg workspace "$1" --arg application "$2"  '.nodes[]|select(.name !="__i3").nodes[]|select(.name==$workspace)|..|objects|select(.name!=null)|select(.name | test($application; "i"))')
echo "$is_emacs_running"

if [[ -z $is_emacs_running ]]; then
  swaymsg exec "$3"
  notify-send -a "Launch" "Launching $3"
else
  echo "not spawning $2"
fi
